project:
  type: book
  output-dir: docs

book:
  title: "STAT 340: Data Science II"
  author: "Brian Powers"
  date: "11/7/2025"
  reader-mode: true
  sidebar:
    collapse-level: 1
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Sampling"
      chapters:
      - probability_rv.qmd
      - R01_Prob_RVs.Rmd
      - rv_practice.qmd
      - text: "---"
      - distributions.qmd
      - R02_Distributions.Rmd
      - distr_practice.qmd
      - text: "---"
      - mc.qmd
      - R03_MonteCarloExamples.Rmd
      - mc_practice.qmd
      - R_MonteCarlo_Battleship.Rmd
    - part: "Testing"
      chapters:
      - testing1.qmd
      - R04_Monte_Carlo_Testing.Rmd
      - testing1_practice.qmd
      - text: "---"
      - testing2.qmd
      - R05_testing_Additional_Examples.Rmd
      - testing2_practice.qmd
    - part: "Estimation"
      chapters:
      - estimation1.qmd
      - R06_More_Estimation_Examples.Rmd
      - estimation1_practice.qmd
      - text: "---"
      - estimation2.qmd
      - R07_More_Estimation_and_CI_Examples.Rmd
      - estimation2_practice.qmd
    - part: "Prediction"
      chapters:
      - prediction1.qmd
      - R08_prediction_examples.Rmd
      - slr_practice.qmd
      - text: "---"
      - prediction2.qmd
      - R09_Multiple_Regression.Rmd
      - mlr_practice.qmd
      - text: "---"
      - logistic.qmd
      - R10_LogisticReg_Extended.rmd
      - logistic_practice.qmd
      - text: "---"
      - cv.qmd
      - R11_cv-MSEcomparison.Rmd
      - R11_Bias_Variance.Rmd
      - R11_Model_Selection.Rmd
      - R11_Ridge_LASSO.Rmd
      - cv_practice.qmd
      - text: "---"
    - part: "Bootstrapping"
      chapters:
      - bootstrap.qmd
      - R12_Bootstrap_Examples.Rmd
      - bootstrap_practice.qmd
  appendices:
    - RV_summary.qmd
bibliography: references.bib

format:
  html:
    theme:
      cosmo
  pdf:
    documentclass: scrreprt

editor: source

